name: Simple Local

on:
  push:

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Check node version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install moment
        run: npm install --save moment

      - name: Run app
        run: node app.js
